Modal Component
fortanix/baklava pull request #5
Opened 2024-10-08 14:28 UTC by nighto

2024-10-10 12:44 UTC, mkrause commented on src/components/overlays/Modal/Modal.tsx
> +  closeable = true,
Please double check whether this also blocks closing using the Escape key.

2024-10-10 12:44 UTC, mkrause requested changes
Block Escape key closing the modal when closeable = false.

2024-10-11 10:02 UTC, mkrause requested changes

2024-10-11 10:05 UTC, nighto commented on src/components/overlays/Modal/Modal.tsx
> +    }
Yeah, I did try that but unfortunately the `cancel` event is fired *after* it closed the dialog, not before. There's also a bug that if you double press Esc, Chrome would close the dialog nevertheless.

https://stackoverflow.com/questions/61021135/prevent-dialog-from-closing-on-keydown-esc-in-chrome

2024-10-11 12:27 UTC, nighto commented on src/components/overlays/Modal/Modal.stories.tsx
>  export const ModalWithSpinner: Story = {
Fixed on latest commit

2024-10-11 12:28 UTC, nighto commented on src/components/overlays/Modal/Modal.tsx
> +export { Modal };
Fixed

2024-10-11 13:30 UTC, mkrause approved these changes

2024-10-11 13:31 UTC, mkrause approved these changes

2024-10-11 13:31 UTC, merged