Banner component update
fortanix/baklava pull request #78
Opened 2024-12-25 23:37 UTC by mkrause

2024-12-30 17:28 UTC, mkrause commented
This apparently caused a regression in Chrome v121, which is the version used on Chromatic at the moment:

![Screenshot 2024-12-30 at 18 25 29](https://github.com/user-attachments/assets/e608b0cc-e25d-4d0b-8aa7-2f707abd5c24)

I cannot reproduce this issue in any modern browser, and just from the screenshots I have not been able to deduce the issue. So this would need some investigation on an actual Chrome v121 instance. On the other hand, Chrome v121 was released in January 2024, so it's almost a year old by now and maybe we can ignore this as an old browser bug.

2025-01-02 14:10 UTC, spli02 requested changes

2025-01-02 14:10 UTC, spli02 commented on src/util/reactDomUtil.ts
> +
Copyright?

2025-01-02 14:10 UTC, spli02 commented on src/util/storybook/storybookUtil.ts
> +export const storyDescription = (description: string) => ({
1. `storyDescription` doesn't seem to be used in the project. Is it necessary to define it?
2. If it's necessary, copyright is missing in this file.

2025-01-02 14:21 UTC, mkrause commented on src/components/containers/Banner/Banner.module.scss
> +          --keep: ;
If a selector has no content it will get stripped by the transpiler. Which breaks CSS modules since we import this selector in the component. We could also remove it entirely from the component, but I think it would be nice to keep these for future use.

2025-01-02 15:12 UTC, mkrause commented on src/util/storybook/storybookUtil.ts
> +export const storyDescription = (description: string) => ({
I was using it for a bit but then find out a docblock can serve the same purpose. Removed this file now.

2025-01-02 15:13 UTC, mkrause commented on src/util/reactDomUtil.ts
> +
Done

2025-01-02 15:24 UTC, mkrause commented on src/components/containers/Banner/Banner.tsx
> +    <TooltipProvider compact tooltip={typeof tooltip !== 'undefined' ? tooltip : buttonProps.label}>
Right, this is sort of on purpose, since the banner itself is in light mode. The banner has a `bk-theme--light` override, so all content within it will be light mode. This seems correct to me, since a dark button on the light banner background would look weird.

For tooltips though: maybe you're right that dark mode would look better for those? Should all tooltips follow the "global" (root) theme maybe? I'll open a ticket for it, think it needs some UX input.

2025-01-02 15:36 UTC, mkrause commented on src/components/actions/Button/Button.tsx
> +  trimmed?: undefined | boolean,
Yeah, good idea. I've added a story.

2025-01-02 16:29 UTC, spli02 approved these changes

2025-01-02 17:02 UTC, merged